### PR TITLE
Some enhancements and new fetures

### PR DESCRIPTION
**Pull request by DariuszPorowski**
- Bumped node packages to the latest
- Added tags to manifest
- Added `ts-node` to run locally for dev testing
- Moved strings to `messages` section to use with loc
- Added predefined - GitleaksUdmCombo.toml (Gitleaks defaults + UDM)
- Added support for report format
  - If report format is sarif then upload to artifact to `CodeAnalysisLogs` - nice report presentation with [SARIF SAST Scans Tab](https://marketplace.visualstudio.com/items?itemName=sariftools.scans) extension
- Added support for depth
- Fixed typo in tests `contsole` -> `console`
- Tests adjusted to report format
- Added tests for sarif report format upload and end with warring
- Codebase lint with ts-standard

### CODE REVIEW

**Comment by DariuszPorowski** [comment]
Hi @JoostVoskuil PTAL :)

**Comment by JoostVoskuil** [comment]
Awesome, very nice! Will check this out this weekend.

Thank you for contributing

**Comment by JoostVoskuil** [comment]
You are my hero this weekend @DariuszPorowski. Never really learned about those Sarif reports but this Is a great asset. Thank you.

**Comment by DariuszPorowski** [comment]
@JoostVoskuil you're welcome. I have some more ideas. If I find time, I'll suggest PR. Your project was inspiration for me and created this one: https://github.com/DariuszPorowski/github-action-gitleaks because official one (https://github.com/marketplace/actions/gitleaks) has very limited capabilities.

**Comment by JoostVoskuil** [comment]
@DariuszPorowski I am honoured ;)

Can you share your thoughts on your ideas? My ideas:
- Include the option that gitleaks can be found on the agent itself (for agents that do not have internet access)
- Do some tweaking regarding fetching the commits between this build and previous.

**Pull request merged**
